<?php $chart_link = $this->getProduct()->getData('c2c_size_chart_link') ?>
<div id="productSizeChart" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <?php if(trim($chart_link) != ''): ?>
                    <iframe height="100%" width="100%" src="<?php echo $chart_link ?>"></iframe>
                <?php else: ?>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('size_charts_block')->toHtml(); ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php $fits_true = $this->getProduct()->getFitsTrue() ?>
<?php $runs_small = $this->getProduct()->getRunsSmall() ?>
<?php $runs_big = $this->getProduct()->getRunsBig() ?>
<div class="sizechart">
    <div class="inner-block">
        <div class="left">
            <a href="#" data-toggle="modal" data-target="#productSizeChart"><?php echo $this->__('Size Chart') ?></a>
        </div>
        <div class="right">
            <i class="icon-size"></i>
            <span><?php echo $this->__('Fits True To Size') ?></span>
        </div>
    </div>
</div>