<?php if($sizeChartUrl = $this->getProduct()->getSizeChart()): ?>
    <iframe src="<?php echo $sizeChartUrl ?>"></iframe>
<?php endif; ?>
<div class="sizechart">
    <div class="inner-block">
        <div class="left">
            <a href="#"><?php echo $this->__('Size Chart') ?></a>
        </div>
        <div class="right">
            <i class="icon-size"></i>
            <span><?php echo $this->__('Fits True To Size') ?></span>
        </div>
    </div>
</div>