<?php
$helper = $this->helper('catalog/output');
$_product = $this->getProduct();
$isWishList = $this->getIsWishlist();
$isCompareList = $this->getIsCompareList();
$isListMode = $this->getIsListMode();
$isCatalogProductList = (bool)$this->getIsProductList();
if($isWishList){
    $_product = $this->getProduct()->getProduct();
}
$imageType = $this->getImageType() ? $this->getImageType() : 'small_image';
?>
<div class="products-item">
    <?php if($isWishList): ?>
        <?php $this->getChild('customer_wishlist_item_remove')->setItem($this->getProduct()); ?>
        <?php echo $this->getChildHtml('customer_wishlist_item_remove'); ?>
    <?php endif; ?>
    <div class="products-item-img">
        <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, $imageType), null, true); ?>" class="product-image">
            <img class="img-responsive" src="<?php echo $this->helper('adaptiveResize/image')->init($_product, 'image')->adaptiveResize(190, 238); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, $imageType), null, true); ?>">
        </a>
    </div>
    <div class="product-shop">
        <h2 class="product-name">
            <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                <?php echo $helper->productAttribute($_product, $_product->getName(), 'name') ?>
            </a>
        </h2>
        <?php echo $this->getPriceHtml($_product, true); ?>
        <?php if (!$isCompareList): ?>
            <?php if($_product->isSaleable()): ?>
                <div class="add-to-cart">
                    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                        <span>
                            <span><?php echo $this->__('Add to Cart') ?></span>
                        </span>
                    </button>
                </div>
            <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
        <?php endif; ?>
        <ul class="add-to-links">
            <?php if(!$isWishList): ?>
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product); ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><span><?php echo $this->__('Add to Wishlist') ?></span></a></li>
                <?php endif; ?>
            <?php endif; ?>
            <?php if(!$isCompareList): ?>
                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                    <li><a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><span><?php echo $this->__('Add to Compare') ?></span></a></li>
                <?php endif; ?>
            <?php endif; ?>
        </ul>
        <?php if (!$isCompareList): ?>
            <?php if ($_product->getShortDescription()): ?>
                <div class="product-description">
                    <?php echo $_product->getShortDescription(); ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>