<?php
$helper = $this->helper('catalog/output');
$_product = $this->getProduct();
$isWishList = $this->getIsWishlist();
$isCompareList = $this->getIsCompareList();
$isListMode = $this->getIsListMode();
if ($_parent = $this->getParentBlock()){
    $modeTool = $_parent->getMode();
} else {
    $modeTool = 'grid';
}
$isCatalogProductList = (bool)$this->getIsProductList();
if($isWishList){
    $_product = $this->getProduct()->getProduct();
}
$imageType = $this->getImageType() ? $this->getImageType() : 'small_image';
?>
<div class="products-item">
    <?php if($modeTool!='grid'): ?><div class="row"><div class="row-height"><div class="col-sm-3 col-height col-middle"><?php endif; ?>
    <?php if($isWishList): ?>
        <?php $this->getChild('customer_wishlist_item_remove')->setItem($this->getProduct()); ?>
        <?php echo $this->getChildHtml('customer_wishlist_item_remove'); ?>
    <?php endif; ?>
    <div class="products-item-img">
        <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, $imageType), null, true); ?>" class="product-image">
            <img class="img-responsive" src="<?php echo $this->helper('adaptiveResize/image')->init($_product, 'image')->adaptiveResize(190, 238); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, $imageType), null, true); ?>">
        </a>
        <?php if($modeTool!='grid'): ?>
            <ul class="add-to-links">
                <?php if(!$isWishList): ?>
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li class="wishlist-link"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product); ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"></a></li>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if(!$isCompareList): ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li class="compare-link"><a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><span><?php echo $this->__('Add to Compare') ?></span></a></li>
                    <?php endif; ?>
                <?php endif; ?>
            </ul>
        <?php endif; ?>
    </div>
    <?php if($modeTool!='grid'): ?></div><?php endif; ?>
    <?php if($modeTool!='grid'): ?><div class="col-sm-7 col-height col-middle"><?php endif; ?>
    <div class="product-shop">
        <h2 class="product-name">
            <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                <?php echo $helper->productAttribute($_product, $_product->getName(), 'name') ?>
            </a>
        </h2>
        <?php if($modeTool=='grid'): ?>
            <?php echo $this->getPriceHtml($_product, true); ?>
            <ul class="add-to-links">
                <?php if(!$isWishList): ?>
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li class="wishlist-link"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product); ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"></a></li>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if(!$isCompareList): ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li class="compare-link"><a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><span><?php echo $this->__('Add to Compare') ?></span></a></li>
                    <?php endif; ?>
                <?php endif; ?>
            </ul>
        <?php endif; ?>
        <?php if (!$isCompareList): ?>
            <?php if ($_product->getShortDescription()): ?>
                <div class="product-description">
                    <?php echo $_product->getShortDescription(); ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?php if($modeTool!='grid'): ?>
        </div>
        <div class="col-sm-2 col-height col-middle">
            <?php echo $this->getPriceHtml($_product, true); ?>
        </div>
    <?php endif; ?>
    <?php if($modeTool!='grid'): ?></div></div><?php endif; ?>
</div>