<?php
/**
 *
 * Copyright (c) 2015 Ecomitize Ltd
 *
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_category  = Mage::getSingleton('catalog/layer')->addAttributeToSelect('featured');
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $productRenderer = $this->getChild('product_renderer');
?>
<?php if(!$_productCollection->count()): ?>
<p><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml(); ?>
    <?php if($this->getMode()!='grid'): ?>
        <?php $_iterator = 0; ?>
        <div class="category-row products-list">
            <?php foreach ($_productCollection as $_product): ?>
                <?php $productRenderer->setProduct($_product); ?>
                <div class="category-item">
                    <?php echo $productRenderer->toHtml(); ?>
                </div>
            <?php endforeach ?>
        </div>
    <?php else: ?>
    <div class="category-row products-grid">
        <?php foreach ($_productCollection as $_product): ?>
            <?php $productRenderer->setProduct($_product); ?>
            <div class="category-item">
                <?php echo $productRenderer->toHtml(); ?>
            </div>
        <?php endforeach ?>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>
