<div class="tabs-wrapper">
    <div class="container">
        <ul class="nav nav-tabs" role="tablist">
            <li class="active"><a href="#related_products" aria-controls="home" data-toggle="tab"><?php echo $this->__('You May Also Like') ?></a></li>
            <li><a href="#product_viewed_block" aria-controls="profile" data-toggle="tab"><?php echo $this->__("Viewed") ?></a></li>
        </ul>
    </div>
</div>
<div class="container-wrapper">
    <div class="container">
        <div class="tab-content">
            <div class="tab-pane active" id="related_products">
                <?php echo $this->getChildHtml('related_products') ?>
            </div>
            <div class="tab-pane" id="product_viewed_block">
                <?php echo $this->getChildHtml('product_viewed_block') ?>
            </div>
        </div>
    </div>
</div>