<?php
    $featuredProducts = $this->getLoadedProductCollection()->addAttributeToSelect('small_image');
    $imageHelper = $this->helper('catalog/image');
?>
<?php if(count($featuredProducts->getItems())): ?>
    <?php if ($this->getTitle()): ?><h3 class="section-title"><?php echo $this->getTitle(); ?></h3><?php endif; ?>
    <div class="carousel">
        <a href="#" class="carousel-controls prev"><i class="icon-left2"></i></a>
        <a href="#" class="carousel-controls next"><i class="icon-right2"></i></a>
        <div class="owl-carousel">
            <?php $productRenderer = $this->getChild('product_renderer'); ?>
            <?php foreach ($featuredProducts as $fp): ?>
                <?php $productRenderer->setProduct($fp); ?>
                <?php echo $productRenderer->toHtml(); ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>