<?php
    $relatedProducts = $this->getProduct()->getRelatedProductIds();
?>
<?php if(count($relatedProducts)): ?>
    <div class="carousel">
        <a href="#" class="carousel-controls prev"><i class="icon-left2"></i></a>
        <a href="#" class="carousel-controls next"><i class="icon-right2"></i></a>
        <div class="owl-carousel" id="block-related">
            <?php $productRenderer = $this->getChild('product_renderer'); ?>
            <?php foreach($relatedProducts as $rp): ?>
                <div class="item">
                    <?php $_rel = Mage::getModel('catalog/product')->load($rp); ?>
                    <?php $productRenderer->setProduct($_rel); ?>
                    <?php echo $productRenderer->toHtml(); ?>
                </div>
            <?php endforeach ?>
        </div>
    </div>
    <script type="text/javascript">
        //<![CDATA[

        var relatedProductsCheckFlag = false;
        function selectAllRelated(txt){
            if (relatedProductsCheckFlag == false) {
                $$('.related-checkbox').each(function(elem){
                    elem.checked = true;
                });
                relatedProductsCheckFlag = true;
                txt.innerHTML="<?php echo Mage::helper('core')->jsQuoteEscape($this->__('unselect all')) ?>";
            } else {
                $$('.related-checkbox').each(function(elem){
                    elem.checked = false;
                });
                relatedProductsCheckFlag = false;
                txt.innerHTML="<?php echo Mage::helper('core')->jsQuoteEscape($this->__('select all')) ?>";
            }
            addRelatedToProduct();
        }

        function addRelatedToProduct(){
            var checkboxes = $$('.related-checkbox');
            var values = [];
            for(var i=0;i<checkboxes.length;i++){
                if(checkboxes[i].checked) values.push(checkboxes[i].value);
            }
            if($('related-products-field')){
                $('related-products-field').value = values.join(',');
            }
        }
        //]]>
    </script>
<?php endif ?>
