<?php if($this->getCollection()->getSize()): ?>
<div class="sorting">
    <div class="row-sorting">
        <?php if( $this->isExpanded() ): ?>
            <div class="col-sorting col-sorting-grid">
                <?php if( $this->isEnabledViewSwitcher() ): ?>
                    <?php $_modes = $this->getModes(); ?>
                    <?php if($_modes && count($_modes)>1): ?>
                        <?php foreach ($this->getModes() as $_code=>$_label): ?>
                            <?php if($this->isModeActive($_code)): ?>
                                <span class="sorting-button"><a class="button active"><i class="icon-<?php echo strtolower($_label) ?>"></i></a></span>
                            <?php else: ?>
                                <span class="sorting-button"><a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="button <?php echo strtolower($_code); ?>"><i class="icon-<?php echo strtolower($_label) ?>"></i></a></span>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
