<?php
$request = $this->getRequest();
$module = $request->getModuleName();
$controller = $request->getControllerName();
$action = $request->getActionName();
?>
<a href="<?php echo $this->getUrl('checkout/cart'); ?>" data-toggle="dropdown" class="top-link-cart">
    <span>
        <span><i class="icon-cart"></i></span>
        <span class="cart-info">
            <span class="cart-title hidden-xs"><?php echo $this->__('My Cart') ?></span>
        <?php
            $count = $this->helper('checkout/cart')->getSummaryCount();
            $total = $this->helper('checkout/cart')->getQuote()->getGrandTotal();
            if (!$count) {$count = 0;}
        ?>
            <span class="cart-figure"><?php echo $count; ?> item(s)</span>
            <span class="hidden-xs"><?php echo $this->__(' - ') ?></span>
            <span class="cart-open-price"><?php echo $this->helper('core')->formatPrice($total, false); ?></span>
        </span>
    </span>
</a>