<?php if(Mage::app()->getFrontController()->getRequest()->getParam('block')): ?>
    <?php
    $items = Mage::getSingleton('checkout/session')->getQuote()->getAllVisibleItems();
    $item = end($items);
    $product = $item->getProduct();
    $qty = $item->getQty();
    $price = $item->getPrice();
    $rendererBlock = Mage::getBlockSingleton('ecomitize_all/product_renderer');
    ?>
    <div class="confirm-product-name">
        <?php echo $product->getName() ?>
    </div>
    <div class="confirm-product-qty-price">
        <span class="confirm-product-qty">
            <?php echo $this->__('QTY:') ?> <?php echo $qty; ?> |
        </span>
        <span class="confirm-product-price">
            <?php echo $rendererBlock->getPriceHtml($product, true) ?>
        </span>
    </div>
    <div class="confirm-product-text">
        <?php echo $this->__('was added to your shopping cart') ?>
    </div>
<?php endif; ?>