<?php if(Mage::app()->getFrontController()->getRequest()->getParam('block')): ?>
    <?php
    $items = Mage::getSingleton('checkout/session')->getQuote()->getAllVisibleItems();
    $item = end($items);
    $product = $item->getProduct();
    $qty = $item->getQty();
    $price = $item->getPrice();
    $rendererBlock = Mage::getBlockSingleton('ecomitize_all/product_renderer');
    ?>
    <div class="product-details">
        <p class="product-name"><?php echo $product->getName() ?></p>
        <div class="info-wrapper">
            <div class="product-qty">
                <?php echo $this->__('QTY:') ?> <?php echo $qty; ?>
            </div>
            <div class="price-box">
            <span class="price">
                <?php echo $rendererBlock->getPriceHtml($product, true) ?>
            </span>
            </div>
        </div>
    </div>
<?php endif; ?>
