<?php if(Mage::app()->getFrontController()->getRequest()->getParam('block')): ?>
    <?php
    $items = Mage::getSingleton('checkout/session')->getQuote()->getAllVisibleItems();
    $item = end($items);
    $product = $item->getProduct();
    $qty = $item->getQty();
    $price = $item->getPrice();
    $rendererBlock = Mage::getBlockSingleton('zen_all/product_renderer');
    $orderOptions = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct());
    ?>
    <div class="product-details">
        <p class="product-name"><?php echo $product->getName() ?></p>
        <div class="info-wrapper">
            <div class="attributes-info">
                <?php if(!empty($orderOptions['attributes_info'])): ?>
                    <?php foreach($orderOptions['attributes_info'] as $option): ?>
                        <div><?php echo $option['label'] . ': ' . $option['value'] ?></div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="bundle-options">
                <?php if(!empty($orderOptions['bundle_options'])): ?>
                    <?php foreach($orderOptions['bundle_options'] as $option): ?>
                        <div><?php echo $option['label'] . ': ' . $option['value'][0]['title'] ?></div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="product-qty">
                <?php echo $this->__('QTY:') ?> <?php echo $qty; ?>
            </div>
            <div class="price-box">
            <span class="price">
                <?php echo $rendererBlock->getPriceHtml($product, true) ?>
            </span>
            </div>
        </div>
    </div>
<?php endif; ?>
