<ul class="nav nav-inline pull-right account-nav">
    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/compare/link.phtml')->toHtml(); ?>
    <?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <li>
            <?php echo $this->getLayout()->createBlock('wishlist/links')->setBlockName('wishlist_link')->toHtml(); ?>
        </li>
    <?php endif; ?>
    <li<?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?> class="dropdown"<?php endif; ?>>
        <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
            <a href="#" data-toggle="modal" data-target="#accountLogin" onclick="logInClick();"><?php echo $this->__('Sign in'); ?></a>
        <?php else: ?>
            <a href="<?php echo $this->getUrl('customer/account'); ?>"><?php echo $this->__('My Account'); ?></a>
        <?php endif; ?>
    </li>
    <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <li>
            <a href="<?php echo $this->getUrl('customer/account/create'); ?>"><?php echo $this->__('Register'); ?></a>
        </li>
    <?php else: ?>
        <li><a href="<?php echo $this->getUrl('customer/account/logout'); ?>"><?php echo $this->__('Logout'); ?></a></li>
    <?php endif; ?>
</ul>
<script type="text/javascript">
    function logInClick() {
        jQuery('body').removeClass('navbar-active');
        jQuery('#navbar').removeClass('in').removeClass('collapse').addClass('collapsed');
    }
</script>