<?php
/**
 * Header template
*/
?>
<button class="active-navbar visible-xs"><i class="icon-close"></i></button>
<div class="backdrop"></div>
<div class="content-wrapper">
    <header>
        <div class="header">
            <div class="header-top">
                <div class="container">
                    <ul class="nav visible-xs">
                        <li class="dropdown pull-right"><a href="#footer-navbar" data-toggle="collapse" data-target="#footer-navbar" aria-controls="footer-navbar" aria-expanded="false"><?php echo $this->__('Links') ?></a></li>
                        <li class="pull-left"><a class="btn-back" href="#"><i class="icon-left text-white"></i><?php echo $this->__('Back') ?></a></li>
                        <li class="pull-left"><a href="tel:<?php echo Mage::getStoreConfig('general/store_information/phone'); ?>"><?php echo Mage::getStoreConfig('general/store_information/phone'); ?></a></li>
                    </ul>
                    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/account-nav.phtml')->toHtml(); ?>
                    <?php echo $this->getChildHtml('topLinks'); ?>
                </div>
            </div>
            <div class="container">
                <div class="header-inner">
                    <div class="row">
                        <div class="row-height">
                            <div class="col-xs-3 col-sm-4 col-xs-height col-xs-middle header-navbar header-contact">
                                <div class="navbar-header">
                                    <button class="navbar-toggle collapsed nav-container-open" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false">
                                        <span></span>
                                        <span></span>
                                        <span></span>
                                    </button>
                                </div>
                                <?php if(Mage::getStoreConfig('general/store_information/phone')): ?>
                                    <span class="header-phone hidden-xs">
                                        <a href="tel:<?php echo Mage::getStoreConfig('general/store_information/phone'); ?>"><?php echo Mage::getStoreConfig('general/store_information/phone'); ?></a>
                                        <a href="<?php echo $this->getUrl('contacts'); ?>"><?php echo $this->__('Contact Us') ?></a>
                                    </span>
                                <?php endif; ?>
                            </div>
                            <div class="col-xs-6 col-sm-4 col-xs-height col-xs-middle header-logo">
                                <?php if ($this->getIsHomePage()):?>
                                    <h1 class="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img class="img-responsive" src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>"></a></h1>
                                <?php else:?>
                                    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img class="img-responsive" src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>"></a>
                                <?php endif?>
                            </div>
                            <div class="col-xs-3 col-sm-4 col-sm-1 col-xs-height col-xs-middle col-sm-push-3 header-cart">
                                <ul class="nav nav-inline header-nav-cart">
                                    <li class="dropdown">
                                        <?php echo $this->getChildHtml('cart_link'); ?>
                                        <ul class="dropdown-menu dropdown-menu-cart pull-right">
                                            <li class="header-minicart">
                                                <?php echo $this->getChildHtml('minicart_head') ?>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-xs-12 col-sm-3 col-sm-height col-sm-middle col-sm-pull-1 header-search">
                                <?php echo $this->getChildHtml('topSearch') ?>
                                <button class="button button-filter collapsed visible-xs" type="button" data-toggle="collapse" data-target=".col-left" aria-controls="col-left" aria-expanded="false">
                                    <span><i class="icon-filter"></i></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('topMenu'); ?>
    </header>