<?php
 /**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Softprodigy
 * @package     Softprodigy_Giftwrap
 * @copyright   Copyright (c) 2013 Softprodigy System Solutions Pvt. Ltd (http://www.softprodigy.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php if($this->getSource() instanceof Mage_Sales_Model_Order): ?>

    <?php if ((float)$this->getSource()->getGiftwrapAmountRefunded() > 0): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper('giftwrap')->__('Giftwrap refunded to customer') ?></strong></td>
            <td><strong><?php echo $this->getSource()->getGiftwrapAmountRefunded(); ?></strong></td>
        </tr>
    <?php endif; ?>

<?php else: ?>

    <?php if ((float)$this->getSource()->getGiftwrapAmount()): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper('giftwrap')->__('Giftwrap Refunded') ?></strong></td>
            <td><strong><?php echo $this->getSource()->getGiftwrapAmount(); ?></strong></td>
        </tr>
    <?php endif;  ?>

<?php endif; ?>

